version: 2.1

executors:
  java-executor:
    docker:
    - image: cimg/openjdk:21.0
    working_directory: ~/project

jobs:
  build:
    executor: java-executor
    steps:
    - checkout

    - run:
        name: Set gradlew permissions
        command: chmod +x ./gradlew

    - run:
        name: Run tests
        command: ./gradlew clean test

    - run:
        name: Save test results
        command: |
          echo "Listing test result directory:"
          cd app/build/test-results/test/
          ls -la
          mkdir -p ~/test-results/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
        when: always

    - store_test_results:
        path: ~/test-results

    - store_artifacts:
        path: ~/test-results
        destination: test-report

    - run:
        name: Notify Microsoft Teams on PASSED
        when: on_success
        command: |
          curl -H "Content-Type: application/json" \
                -d '{
                    "@type": "MessageCard",
                    "@context": "http://schema.org/extensions",
                    "summary": "CircleCI Job PASS",
                    "themeColor": "#28a745",
                    "title": "CircleCI Job Notify",
                    "text": "Job **build** in CircleCI done."
                  }' \
                $TEAMS_WEBHOOK_URL
    - run:
        name: Notify Microsoft Teams on FAILED
        when: on_fail
        command: |
          curl -H "Content-Type: application/json" \
                -d '{
                    "@type": "MessageCard",
                    "@context": "http://schema.org/extensions",
                    "summary": "CircleCI Job FAILED",
                    "themeColor": "FF0000",
                    "title": "CircleCI Job Notify",
                    "text": "Job **build** in CircleCI FAILED. Please check the logs."
                  }' \
                $TEAMS_WEBHOOK_URL

workflows:
  build-and-test:
    jobs:
    - build:
        context: SonarCloud
