/*
 * This source file was generated by the Gradle 'init' task
 */
package demojava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void getSum() {
        assertEquals(2, App.getSum(2, 0));
        assertEquals(11, App.getSum(4, 7));
        assertEquals(3, App.getSum(3, -2));
    }

    @Test
    void getSub() {
        assertEquals(-2, App.getSub(1, 4));
        assertEquals(4, App.getSub(11, 7));
    }
}
