/*
 * This source file was generated by the Gradle 'init' task
 */
package demojava;

import java.util.logging.Logger;

public class App {
    Logger logger = Logger.getLogger(getClass().getName());

    public String getGreeting() {
        return "Hello World!";
    }

    public static int getSum(int num1, int num2) {
        return num1 + num2;
    }

    public static int getSub(int num1, int num2) {
        return num1 - num2;
    }

    public void main(String[] args) {
        logger.info(new App().getGreeting());
        System.out.println("Reusult = " + getSum(4, 7));
        logger.info("Done!");
    }
}
