/*
 * This source file was generated by the Gradle 'init' task
 */
package demojava;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static int getSum(int num1, int num2) {
        return num1 + num2;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Reusult = " + getSum(4, 7));
    }
}
